paths:
  data_dir: data
  cache_dir: data_cache
  models_dir: models
  fastf1_cache: .fastf1

runtime:
  random_seed: 42
  n_jobs: 4

fastf1:
  enable_cache: true
  offline: false

model:
  baseline: gradient_boosting
  advanced: xgboost

evaluation:
  cv_scheme: season_split
  metrics:
    - top3_accuracy
    - top10_accuracy
    - lap_mae
    - interval_rmse 